### ISSUE TITLE
Couldn't run scenario.py

### ISSUE THREAD

**Issue by hizamighani** [patriciaOrtuno28/Demo-MicrosoftSEAL-Python#1]
An error occur once i run `python3 scenario.py`

The error is as below:
```Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/simplefhe/__init__.py", line 6, in <module>
    from seal import *
ModuleNotFoundError: No module named 'seal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/j3mmyy/Demo-MicrosoftSEAL-Python/SEAL-Python/scenario.py", line 4, in <module>
    from simplefhe import generate_keypair
  File "/usr/local/lib/python3.10/dist-packages/simplefhe/__init__.py", line 8, in <module>
    raise ModuleNotFoundError('simplefhe depends on the SEAL-Python library. See https://github.com/Huelse/SEAL-Python for installation instructions.')
ModuleNotFoundError: simplefhe depends on the SEAL-Python library. See https://github.com/Huelse/SEAL-Python for installation instructions.```

**Comment by patriciaOrtuno28** [comment]
> An error occur once i run `python3 scenario.py`
> 
> The error is as below:
> 
> ```
>   File "/usr/local/lib/python3.10/dist-packages/simplefhe/__init__.py", line 6, in <module>
>     from seal import *
> ModuleNotFoundError: No module named 'seal'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/j3mmyy/Demo-MicrosoftSEAL-Python/SEAL-Python/scenario.py", line 4, in <module>
>     from simplefhe import generate_keypair
>   File "/usr/local/lib/python3.10/dist-packages/simplefhe/__init__.py", line 8, in <module>
>     raise ModuleNotFoundError('simplefhe depends on the SEAL-Python library. See https://github.com/Huelse/SEAL-Python for installation instructions.')
> ModuleNotFoundError: simplefhe depends on the SEAL-Python library. See https://github.com/Huelse/SEAL-Python for installation instructions.```
> ```

Hi, I haven't really given support to this repository in a year. For now, I'd recommend you to use the Linux installation, as that one works perfectly.
I have included a new Dockerfile and instructions to run in Docker but it is not working at the moment. If I have time to fix it I will notify you on this issue, therefore I will leave it open.
Best regards.
